version: "3"
services:
  mikanos:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "6080:6080"
    volumes:
      - ./chapters:/usr/chapters
      # - /dev/disk2s1:/dev/disk2s1
    #   - ~/.Xauthority:/root/.Xauthority
    # environment:
    #   - DISPLAY
    tty: true
    stdin_open: true
    privileged: true
